// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrgSampleApi.Sample.Data;

#nullable disable

namespace OrgSampleApi.Sample.Data.Migrations
{
    [DbContext(typeof(OrgSampleDbContext))]
    [Migration("20251026222408_CreateOrganizationInvitations")]
    partial class CreateOrganizationInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrgSampleApi.Sample.Data.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrganizationSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RoleIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Code")
                        .HasName("PK_Identity_OrganizationInvitations");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Identity_OrganizationInvitations_Email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_Identity_OrganizationInvitations_OrganizationId");

                    b.ToTable("Identity_OrganizationInvitations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
