// <auto-generated />
using System;
using Identity.Base.Organisations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Base.Organisations.Data.Migrations
{
    [DbContext(typeof(OrganisationDbContext))]
    partial class OrganisationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Base.Organisations.Data.Entities.OrganisationInvitationEntity", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrganisationSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RoleIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Code")
                        .HasName("PK_Identity_OrganisationInvitations");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Identity_OrganisationInvitations_Email");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("IX_Identity_OrganisationInvitations_OrganisationId");

                    b.HasIndex("UsedAtUtc")
                        .HasDatabaseName("IX_Identity_OrganisationInvitations_UsedAtUtc");

                    b.ToTable("Identity_OrganisationInvitations", (string)null);
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DisplayName")
                        .IsUnique()
                        .HasDatabaseName("IX_Organisations_Tenant_DisplayName");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Organisations_Tenant_Slug");

                    b.ToTable("Identity_Organisations", (string)null);
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationMembership", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganisationId", "UserId");

                    b.HasIndex("OrganisationId", "CreatedAtUtc")
                        .HasDatabaseName("IX_OrganisationMemberships_Organisation_Created");

                    b.HasIndex("OrganisationId", "UserId")
                        .HasDatabaseName("IX_OrganisationMemberships_Organisation_User");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("IX_OrganisationMemberships_User_Tenant");

                    b.ToTable("Identity_OrganisationMemberships", (string)null);
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId", "OrganisationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_OrganisationRoles_Tenant_Organisation_Name");

                    b.ToTable("Identity_OrganisationRoles", (string)null);
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationRoleAssignment", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganisationId", "UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_OrganisationRoleAssignments_Role");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("IX_OrganisationRoleAssignments_User_Tenant");

                    b.ToTable("Identity_OrganisationRoleAssignments", (string)null);
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "RoleId")
                        .HasDatabaseName("IX_OrganisationRolePermissions_Organisation_Role");

                    b.HasIndex("RoleId", "PermissionId")
                        .HasDatabaseName("IX_OrganisationRolePermissions_Role_Permission");

                    b.HasIndex("TenantId", "RoleId")
                        .HasDatabaseName("IX_OrganisationRolePermissions_Tenant_Role");

                    b.ToTable("Identity_OrganisationRolePermissions", (string)null);
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationMembership", b =>
                {
                    b.HasOne("Identity.Base.Organisations.Domain.Organisation", "Organisation")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationRole", b =>
                {
                    b.HasOne("Identity.Base.Organisations.Domain.Organisation", "Organisation")
                        .WithMany("Roles")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationRoleAssignment", b =>
                {
                    b.HasOne("Identity.Base.Organisations.Domain.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Base.Organisations.Domain.OrganisationRole", "Role")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Identity.Base.Organisations.Domain.OrganisationMembership", "Membership")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("OrganisationId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");

                    b.Navigation("Organisation");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationRolePermission", b =>
                {
                    b.HasOne("Identity.Base.Organisations.Domain.OrganisationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.Organisation", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationMembership", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Identity.Base.Organisations.Domain.OrganisationRole", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
