// <auto-generated />
using System;
using Identity.Base.ServicePrincipals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Base.Host.PostgreSqlMigrations.Data.Migrations.ServicePrincipals
{
    [DbContext(typeof(ServicePrincipalDbContext))]
    [Migration("20260720125256_AddServicePrincipals")]
    partial class AddServicePrincipals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Base.ServicePrincipals.Domain.ServicePrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("IX_Host_ServicePrincipals_ClientId");

                    b.ToTable("Host_ServicePrincipals", (string)null);
                });

            modelBuilder.Entity("Identity.Base.ServicePrincipals.Domain.ServicePrincipalCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ServicePrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServicePrincipalId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Host_ServicePrincipalCredentials_Principal_Name");

                    b.ToTable("Host_ServicePrincipalCredentials", (string)null);
                });

            modelBuilder.Entity("Identity.Base.ServicePrincipals.Domain.ServicePrincipalCredential", b =>
                {
                    b.HasOne("Identity.Base.ServicePrincipals.Domain.ServicePrincipal", "ServicePrincipal")
                        .WithMany("Credentials")
                        .HasForeignKey("ServicePrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePrincipal");
                });

            modelBuilder.Entity("Identity.Base.ServicePrincipals.Domain.ServicePrincipal", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
